import = ["~/.config/alacritty/themes/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "MesloLGS NF"

[font.italic]
style = "Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"

[scrolling]
history = 1000

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 98
lines = 28

[window.padding]
x = 0
y = 0

# macOS copy/paste
[[keyboard.bindings]]
action  = "Paste"
key = "v"
mods = "Command"

[[keyboard.bindings]]
action  = "Copy"
key = "c"
mods = "Command"

[[keyboard.bindings]]
action  = "ToggleFullscreen"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0015"
key = "Backspace"
mods = "Command"

[[keyboard.bindings]]
key = "K"
mods = "Command"
mode = "~Vi|~Search"
action = "ClearHistory"
